# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e5c40e5850fb89f02bf2846e9e82f98a829104b89ab1eeefdf6a30bf63f515dc3e09b609d6cd19ca0639795a4fcad5209c9fc3a127ec98b1a11e1d215926a01

test:
  secret_key_base: 8c3a58b3a9bbc611e396c21aa76cc505dab572d3f4d9b4e27c3fbf3cb3c2f56d70068a75cb20608f9eed9ddce4aa87b4ad427fbc833db372bbc031a69568052f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
